### ISSUE TITLE
readme is only informative with images

### ISSUE THREAD

**Issue by sparr** [kurehajime/pong-command#2]
The readme contains little to no explanatory information without loading and playing the animated image. A sentence or two would be very useful.

**Comment by christianbundy** [comment]
:+1:

``` markdown
### How to use.

Type `pong <IP Address>` .

![pong](https://cloud.githubusercontent.com/assets/4569916/7273449/e6c410be-e92e-11e4-89dd-ba6903089706.gif)


### download

[Download here. Windows,OSX,Linux binary](https://github.com/kurehajime/pong-command/releases/tag/0.1)

### build

```

``` sh

git clone https://github.com/kurehajime/pong-command.git
go get -u github.com/nsf/termbox-go
go build pong-command/pong/pong.go

```

A bit more text documentation would be _super_ useful for viewing this in text form.

**Comment by kurehajime** [comment]
Thank you for advice .
I added a little explanation to the readme text .
But,I'm poor at English. 
If someone wrote a better readme text, I want to use it .
